name: MLops CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      

      - name: Build Docker images
        run: |
          docker build -t jithinkrishna26/fastapi:dev .
          docker build -t jithinkrishna26/streamlit:dev ./streamlit_app

      - name: Push Docker images to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            jithinkrishna26/fastapi:dev
            jithinkrishna26/streamlit:dev



